Experiment with MacOS CI

diff --git a/.github/workflows/pre-build.yml b/.github/workflows/pre-build.yml
--- a/.github/workflows/pre-build.yml
+++ b/.github/workflows/pre-build.yml
@@ -29,6 +29,61 @@ jobs:
         cmake -DCMAKE_BUILD_TYPE=Release ../src
         make
         macdeployqt Pilorama.app -qmldir=../src -appstore-compliant
+    - name: Fetch Certificate
+      env:
+        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
+        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
+      run: |
+        bundle exec fastlane ios certificates
+    - name: Codesign
+      run: |
+        codesign \
+         --sign "Developer ID Application: SIGONNA LLC (BF7ZL72794)" \
+         --timestamp \
+         --options runtime \
+         --force \
+         --deep \
+         Pilorama.app
+    - name: Notarize Application
+      env:
+        ICLOUD_USER: ${{ secrets.ICLOUD_USER }}
+        ICLOUD_PASSWORD: ${{ secrets.ICLOUD_PASSWORD }}
+      run: |
+        echo "Zipping application bundle..."
+        ditto -c -k --keepParent Pilorama.app Pilorama.zip
+        echo "Uploading for notarization..."
+        UUID=$( \
+          xcrun altool \
+           --notarize-app \
+           --primary-bundle-id "com.sigonna.opensource.Pilorama" \
+           -u "$ICLOUD_USER" -p "$ICLOUD_PASSWORD" \
+           --file Pilorama.zip | \
+          egrep "RequestUUID" | \
+          egrep -o '[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}' \
+        )
+        echo "Successfully uploaded UUID: $UUID"
+        STATUS="In Progress"
+        TRIES=1
+        echo "Waiting for notarization..."
+        while [[ $STATUS != "Package Approved" ]]
+        do
+          echo "- attempt $TRIES..."
+          if [[ $TRIES == 30 ]]
+          then
+            echo "Notarization FAILED"
+            exit 1
+          fi
+          sleep 30s
+          STATUS=$( \
+            xcrun altool \
+             --notarization-info "$UUID" \
+             -u "$ICLOUD_USER" -p "$ICLOUD_PASSWORD" | \
+            egrep -o "Package Approved" || : \
+          )
+          (( TRIES++ ))
+          echo "  in progress"
+        done
+        xcrun stapler staple "Pilorama.app"
     - name: Make Installer
       run: |
         mkdir executable
